#docker-compose.yaml
version: '2.1'
services:
  web:
    image: lpshanley/octobercms:latest
    ports:
      - 80:80
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_DATABASE=octobercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - QUEUE_DRIVER=database
      - SESSION_DRIVER=database
      - TZ=CST
      - APP_DEBUG=true
      - OCTOBER_CMS_BACKEND_URI=admin
      - OCTOBER_PLUGINS=Flynsarmy.IdeHelper;RainLab.Builder;RainLab.User;KurtJensen.Passage;ToughDeveloper.ImageResizer;RainLab.Editable;VojtaSvoboda.TwigExtensions;RainLab.GoogleAnalytics;Bedard.AnalyticsExtension;Indikator.Backend;Renatio.DynamicPDF;Inetis.Dump;
      - GIT_THEMES=https://github.com/lpshanley/FW-Dashboard.git;
      - CMS_ACTIVE_THEME=FW-Dashboard
      - GIT_PLUGINS=https://github.com/lpshanley/IMS.git;
    volumes:
      - ./data/plugins/lpshanley:/var/www/html/plugins/lpshanley
      - ./data/themes:/var/www/html/themes
      - ./data/storage/logs:/var/www/html/storage/logs
      - ./data/storage/temp:/var/www/html/storage/temp
      - ./data/storage/app:/var/www/html/storage/app
  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=octobercms
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306